import { MathFormulaParser } from '../src';

const parser = new MathFormulaParser();

const expressions = [
    'sin(pi/4)^2 + cos(pi/4)^2',
    'log(e^x) + sqrt(x^2 + y^2)',
    'exp(sin(x)*cos(y)) - tan(z)',
    'sqrt(abs(x^3 - y^3)) + cbrt(z)',
    'log10(1000) + ln(e^2)',
    'phi^2 - phi - 1',
    'gamma + digamma(5)',
    'sin(x)^2 + cos(x)^2 + tan(x)^2',
    'arcsin(sin(x/2)) + arccos(cos(x/3))',
    'sinh(x) * cosh(y) - tanh(z)',
    'asinh(x) + acosh(y+1) + atanh(z/2)',
    'exp(log(x+y))',
    'sqrt2 * sqrt3 / sqrt5',
    'pow(x,3) + root(27,3)',
    'abs(-x) + sign(-y)',
    'round(pi) + floor(e) + ceil(phi)',
    'frac(pi) + integer(e)',
    'max(x,y,z) - min(x,y,z)',
    'mod(x,5) + rem(y,3)',
    'gcd(48,18) + lcm(12,15)',
    'factorial(5) + fact(6)',
    'choose(10,3) + perm(6,2)',
    'comb(8,4) * factorial(3)',
    'beta(2,3) + betainc(0.5,2,3)',
    'erf(x) + erfc(x)',
    'erfinv(0.5)',
    'bessel_j(1,x) + bessel_y(2,x)',
    'bessel_i(0,x) + bessel_k(1,x)',
    'elliptic_k(0.5) + elliptic_e(0.5)',
    'sinc(x) + sigmoid(x)',
    'logit(0.3) + softsign(x)',
    'mean(1,2,3,4,5)',
    'median(1,3,5,7,9)',
    'variance(1,2,3,4,5)',
    'stddev(1,2,3,4,5)',
    'skewness(1,2,3,4,5)',
    'kurtosis(1,2,3,4,5)',
    'covariance(x,y)',
    'correlation(x,y)',
    'quantile(0.75,1,2,3,4,5)',
    'percentile(90,1,2,3,4,5)',
    'normpdf(x,0,1)',
    'normcdf(x,0,1)',
    'norminv(0.95,0,1)',
    'pdf(x)',
    'cdf(x)',
    'pmf(k)',
    'sum(i,1,n,i^2)',
    'product(i,1,n,i)',
    'integral(x,0,1,x^2)',
    'integral(x,0,pi,sin(x))',
    'derivative(x^3,x)',
    'diff(sin(x),x)',
    'partial(x^2*y,x)',
    'limit(sin(x)/x,x,0)',
    'lim((1+1/n)^n,n,infinity)',
    'matrix(1,2;3,4)',
    'vector(1,2,3)',
    'det(matrix(1,2;3,4))',
    'trace(matrix(1,2;3,4))',
    'rank(matrix(1,0;0,1))',
    'norm(vector(3,4))',
    'transpose(matrix(1,2;3,4))',
    'inv(matrix(1,2;3,4))',
    'eig(matrix(1,2;3,4))',
    'svd(matrix(1,2;3,4))',
    'dot(vector(1,2,3),vector(4,5,6))',
    'cross(vector(1,0,0),vector(0,1,0))',
    'hadamard(matrix(1,2;3,4),matrix(5,6;7,8))',
    'hypot(x,y)',
    'atan2(y,x)',
    'copysign(x,y)',
    'ldexp(x,3)',
    'frexp(x)',
    'fmod(x,y)',
    'fma(x,y,z)',
    'next(x)',
    'prev(x)',
    'ulp(x)',
    '(x+y)*(x-y)',
    '(x^2 + y^2) / (1 + sqrt(x*y))',
    '(sin(x)+cos(y))^2',
    '(exp(x)-1)/(expm1(x))',
    'log1p(x) - ln(1+x)',
    '!(x > y)',
    '(x > y) && (y > z)',
    '(x < y) || (y < z)',
    '(x == y) != (y == z)',
    '(x >= y) && (y <= z)',
    '(x + y + z) / 3',
    'sqrt(x^2 + y^2 + z^2)',
    'sin(cos(tan(x)))',
    'exp(sin(cos(tan(x))))',
    'sqrt(abs(sin(x^2 - y^2)))',
    'log(abs(x*y*z))',
    'exp(pi*i) + 1',
    'sin(pi*x) / (pi*x)',
    '(1 + 1/n)^n',
    'gamma(x+1)',
    'digamma(x) - ln(x)',
    '(phi^n - (-phi)^(-n))/sqrt5',
    '(sqrt5 + 1)/2',
    '(sqrt5 - 1)/2',
    '(x+y+z)^3 - 3*(x+y)*(y+z)*(z+x)',
];
