export enum TokenType {
    WHITESPACE = 'WHITESPACE',
    NUMBER = 'NUMBER',
    IDENTIFIER = 'IDENTIFIER',
    PLUS = 'PLUS',
    MINUS = 'MINUS',
    MULTIPLY = 'MULTIPLY',
    DIVIDE = 'DIVIDE',
    POWER = 'POWER',
    MODULO = 'MODULO',
    EQUAL = 'EQUAL',
    NOT_EQUAL = 'NOT_EQUAL',
    LESS_THAN = 'LESS_THAN',
    GREATER_THAN = 'GREATER_THAN',
    LESS_EQUAL = 'LESS_EQUAL',
    GREATER_EQUAL = 'GREATER_EQUAL',
    AND = 'AND',
    OR = 'OR',
    NOT = 'NOT',
    LPAREN = 'LPAREN',
    RPAREN = 'RPAREN',
    LBRACKET = 'LBRACKET',
    RBRACKET = 'RBRACKET',
    LBRACE = 'LBRACE',
    RBRACE = 'RBRACE',
    COMMA = 'COMMA',
    SEMICOLON = 'SEMICOLON',
    COLON = 'COLON',
    INTEGRAL = 'INTEGRAL',
    SUMMATION = 'SUMMATION',
    PRODUCT = 'PRODUCT',
    SQRT = 'SQRT',
    DERIVATIVE = 'DERIVATIVE',
    PARTIAL = 'PARTIAL',
    FACTORIAL = 'FACTORIAL',
    UNDER = 'UNDER',
    ELLIPSIS = 'ELLIPSIS',
    EOF = 'EOF'
};

export const MATH_CONSTANTS: Record< string, number > = {
    pi: Math.PI,
    e: Math.E,
    phi: ( 1 + Math.sqrt( 5 ) ) / 2,
    golden: ( 1 + Math.sqrt( 5 ) ) / 2,
    infinity: Infinity,
    nan: NaN,
    gamma: 0.5772156649,
    sqrt2: Math.sqrt( 2 ),
    sqrt3: Math.sqrt( 3 ),
    sqrt5: Math.sqrt( 5 ),
    ln2: Math.log( 2 ),
    ln10: Math.log( 10 )
};
