/**
 * Common types, interfaces, and enums used throughout the Math Formula Parser library.
 * 
 * This file defines the core data structures for tokens, operators, positions,
 * and analysis results, ensuring type safety and consistency across the project.
 * 
 * @author Paul Köhler
 * @license MIT
 */

import type { ASTNode } from './ast';


/** Enum representing all supported token types during lexical analysis. */
export enum TokenType {
    WHITESPACE = 'WHITESPACE',
    NUMBER = 'NUMBER',
    IDENTIFIER = 'IDENTIFIER',
    PLUS = 'PLUS',
    MINUS = 'MINUS',
    MULTIPLY = 'MULTIPLY',
    DIVIDE = 'DIVIDE',
    POWER = 'POWER',
    MODULO = 'MODULO',
    EQUAL = 'EQUAL',
    NOT_EQUAL = 'NOT_EQUAL',
    LESS_THAN = 'LESS_THAN',
    GREATER_THAN = 'GREATER_THAN',
    LESS_EQUAL = 'LESS_EQUAL',
    GREATER_EQUAL = 'GREATER_EQUAL',
    AND = 'AND',
    OR = 'OR',
    NOT = 'NOT',
    UNDER = 'UNDER',
    LPAREN = 'LPAREN',
    RPAREN = 'RPAREN',
    LBRACKET = 'LBRACKET',
    RBRACKET = 'RBRACKET',
    COMMA = 'COMMA',
    SEMICOLON = 'SEMICOLON',
    ELLIPSIS = 'ELLIPSIS',
    EOF = 'EOF'
}

/** Supported associativity types for operators. */
export type Associativity = 'left' | 'right';

/** Specification for a mathematical operator. */
export interface OperatorSpec {
    symbol: string;
    token: TokenType;
    precedence: number;
    associativity: Associativity;
    isPrefix?: boolean;
    isPostfix?: boolean;
    description?: string;
    label?: string;
}

/** Function type for creating new AST nodes. */
export type NodeFactory = ( kind: string, props: Record< string, any >, position?: Position ) => ASTNode;

/** Function type for custom function builders. */
export type FunctionBuilder = ( create: NodeFactory, args: ASTNode[], position?: Position ) => ASTNode;

/** Function type for retrieving children from an AST node. */
export type ChildrenGetter = ( node: ASTNode ) => ASTNode[];

/** Function type for generating a label for an AST node. */
export type Labeler = ( node: ASTNode, options: VisualizationOptions ) => string;

/** Function type for converting an AST node to a string. */
export type Stringifier = ( node: ASTNode, parentPrecedence: number ) => string;

/** Represents a position within a source formula string. */
export interface Position {
    line: number;
    column: number;
    offset: number;
}

/** Represents a single token generated by the lexer. */
export interface Token {
    type: TokenType;
    value: string;
    position: Position;
}

/** Defines a pattern for identifying a specific token type. */
export interface TokenPattern {
    regex: RegExp;
    type: TokenType;
    skip?: boolean;
}

/** Represents the result of a comprehensive formula analysis. */
export interface AnalysisResult {
    ast: ASTNode;
    variables: Set< string >;  
    constants: Set< string >;  
    functions: Set< string >;  
    depth: number;  
    nodeCount: number;  
    string: string;  
}

/** Overview of the supported instruction set. */
export interface InstructionSet {
    version: string;
    constants: string[];
    functions: string[];
    operators: string[];
}

/** Configuration options for AST visualization. */
export interface VisualizationOptions {
    showTypes?: boolean;
    showPositions?: boolean;
    indentSize?: number;
    compact?: boolean;
}
